debug = true

name = "Goatpass"
maintainer = "SmartSheep Studio"

bind = "0.0.0.0:8444"
grpc_bind = "0.0.0.0:7444"
domain = "id.smartsheep.studio"
secret = "LtTjzAGFLshwXhN4ZD4nG5KlMv1MWcsvfv03TSZYnT1VhiAnLIZFTnHUwR0XhGgi"

content = "uploads"

use_registration_magic_token = false

[external.firebase]
credentials = "dist/firebase-certs.json"

[mailer]
name = "Alphabot <alphabot@smartsheep.studio>"
smtp_host = "smtp.exmail.qq.com"
smtp_port = 465
username = "alphabot@smartsheep.studio"
password = "gz937Zxxzfcd9SeH"

[security]
cookie_domain = "localhost"
cookie_samesite = "Lax"
auto_signoff_duration = 86400
access_token_duration = 300
refresh_token_duration = 2592000

[database]
dsn = "host=localhost dbname=hy_identity port=5432 sslmode=disable"
prefix = "identity_"
