id = "passport01"
name = "Solarpass"

bind = "0.0.0.0:8444"
grpc_bind = "0.0.0.0:7444"
domain = "localhost"

domain = "id.solsynth.dev"

content_endpoint = "https://usercontent.solsynth.dev"

default_user_group = 1

use_registration_magic_token = false

[debug]
database = false
print_routes = false

[dealer]
addr = "127.0.0.1:7442"

[security]
issuer = "https://solsynth.dev"
cookie_domain = "localhost"
cookie_samesite = "Lax"
access_token_duration = 300
refresh_token_duration = 2592000

[database]
dsn = "host=localhost user=postgres password=password dbname=hy_passport port=5432 sslmode=disable"
prefix = "passport_"
