id = "passport01"
name = "Solarpass"

bind = "0.0.0.0:8003"
grpc_bind = "0.0.0.0:7003"
domain = "id.solsynth.dev"

frontend_app = "https://solsynth.dev"

content_endpoint = "https://usercontent.solsynth.dev"

default_user_group = 1

use_registration_magic_token = false

nexus_addr = "localhost:7001"

[debug]
database = false
print_routes = false

[security]
issuer = "https://solsynth.dev"
cookie_domain = "localhost"
cookie_samesite = "Lax"
access_token_duration = 300
refresh_token_duration = 2592000
internal_public_key = "keys/internal_public_key.pem"
